# http://patorjk.com/software/taag/#p=display&f=Big%20Money-ne&t=Godxvincent%20
spring:
  banner:
    charset: UTF-8
    location: banners/banner.txt
  datasource:
    password: 4ndres2019$1
    username: db_rvargas
    url: jdbc:mysql://localhost:3306/db_rvargas_test?useSSL=false
  jpa:
    show-sql: true
    hibernate:      ddl-auto: update
      naming:        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # globally_quoted_identifiers: true
        
          
server:
  error:
    whitelabel:
      enabled: true
  port: 9000
  

    